# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'contents.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_contentsUI(object):
    def setupUi(self, contentsUI):
        contentsUI.setObjectName("contentsUI")
        contentsUI.setEnabled(True)
        contentsUI.resize(1099, 537)
        contentsUI.setMinimumSize(QtCore.QSize(1099, 537))
        contentsUI.setMaximumSize(QtCore.QSize(1099, 537))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        contentsUI.setFont(font)
        self.back = QtWidgets.QPushButton(contentsUI)
        self.back.setGeometry(QtCore.QRect(10, 500, 75, 23))
        self.back.setObjectName("back")
        self.welcomeMessage = QtWidgets.QTextBrowser(contentsUI)
        self.welcomeMessage.setEnabled(False)
        self.welcomeMessage.setGeometry(QtCore.QRect(20, 20, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        self.welcomeMessage.setFont(font)
        self.welcomeMessage.setMouseTracking(False)
        self.welcomeMessage.setFocusPolicy(QtCore.Qt.NoFocus)
        self.welcomeMessage.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.welcomeMessage.setAcceptDrops(False)
        self.welcomeMessage.setAutoFillBackground(False)
        self.welcomeMessage.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.welcomeMessage.setFrameShadow(QtWidgets.QFrame.Plain)
        self.welcomeMessage.setObjectName("welcomeMessage")
        self.abstract_2 = QtWidgets.QTextBrowser(contentsUI)
        self.abstract_2.setGeometry(QtCore.QRect(10, 170, 661, 241))
        self.abstract_2.setObjectName("abstract_2")
        self.title = QtWidgets.QLineEdit(contentsUI)
        self.title.setGeometry(QtCore.QRect(10, 80, 661, 20))
        self.title.setObjectName("title")
        self.author = QtWidgets.QLineEdit(contentsUI)
        self.author.setGeometry(QtCore.QRect(10, 110, 661, 20))
        self.author.setObjectName("author")
        self.date = QtWidgets.QLineEdit(contentsUI)
        self.date.setGeometry(QtCore.QRect(10, 140, 131, 20))
        self.date.setObjectName("date")
        self.url = QtWidgets.QLineEdit(contentsUI)
        self.url.setGeometry(QtCore.QRect(10, 420, 661, 20))
        self.url.setObjectName("url")

        self.retranslateUi(contentsUI)
        QtCore.QMetaObject.connectSlotsByName(contentsUI)

    def retranslateUi(self, contentsUI):
        _translate = QtCore.QCoreApplication.translate
        contentsUI.setWindowTitle(_translate("contentsUI", "searchUI"))
        self.back.setText(_translate("contentsUI", "Back"))
        self.welcomeMessage.setHtml(_translate("contentsUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Calibri Light\',\'Calibri\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\">Coventry University | Research Grid</span></p></body></html>"))
        self.abstract_2.setHtml(_translate("contentsUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Calibri\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Abstract</p></body></html>"))
        self.title.setText(_translate("contentsUI", "Title"))
        self.author.setText(_translate("contentsUI", "Author"))
        self.date.setText(_translate("contentsUI", "Date"))
        self.url.setText(_translate("contentsUI", "Url"))
