# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_searchUI(object):
    def setupUi(self, searchUI):
        searchUI.setObjectName("searchUI")
        searchUI.setEnabled(True)
        searchUI.resize(1099, 537)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(searchUI.sizePolicy().hasHeightForWidth())
        searchUI.setSizePolicy(sizePolicy)
        searchUI.setMinimumSize(QtCore.QSize(1099, 537))
        searchUI.setMaximumSize(QtCore.QSize(1099, 537))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        searchUI.setFont(font)
        self.welcomeMessage = QtWidgets.QTextBrowser(searchUI)
        self.welcomeMessage.setEnabled(False)
        self.welcomeMessage.setGeometry(QtCore.QRect(270, 20, 551, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        self.welcomeMessage.setFont(font)
        self.welcomeMessage.setMouseTracking(False)
        self.welcomeMessage.setFocusPolicy(QtCore.Qt.NoFocus)
        self.welcomeMessage.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.welcomeMessage.setAcceptDrops(False)
        self.welcomeMessage.setAutoFillBackground(False)
        self.welcomeMessage.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.welcomeMessage.setFrameShadow(QtWidgets.QFrame.Plain)
        self.welcomeMessage.setObjectName("welcomeMessage")
        self.exit = QtWidgets.QPushButton(searchUI)
        self.exit.setGeometry(QtCore.QRect(10, 500, 75, 23))
        self.exit.setObjectName("exit")
        self.quote = QtWidgets.QTextBrowser(searchUI)
        self.quote.setEnabled(False)
        self.quote.setGeometry(QtCore.QRect(280, 70, 551, 51))
        self.quote.setMouseTracking(False)
        self.quote.setFocusPolicy(QtCore.Qt.NoFocus)
        self.quote.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.quote.setAcceptDrops(False)
        self.quote.setAutoFillBackground(False)
        self.quote.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.quote.setFrameShadow(QtWidgets.QFrame.Plain)
        self.quote.setObjectName("quote")
        self.sendQuary = QtWidgets.QPushButton(searchUI)
        self.sendQuary.setGeometry(QtCore.QRect(740, 130, 71, 31))
        self.sendQuary.setCheckable(False)
        self.sendQuary.setChecked(False)
        self.sendQuary.setDefault(False)
        self.sendQuary.setFlat(False)
        self.sendQuary.setObjectName("sendQuary")
        self.searchQuary = QtWidgets.QTextEdit(searchUI)
        self.searchQuary.setGeometry(QtCore.QRect(260, 130, 481, 31))
        self.searchQuary.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.searchQuary.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.searchQuary.setObjectName("searchQuary")
        self.tableView = QtWidgets.QTableView(searchUI)
        self.tableView.setGeometry(QtCore.QRect(25, 200, 1041, 281))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView.sizePolicy().hasHeightForWidth())
        self.tableView.setSizePolicy(sizePolicy)
        self.tableView.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setDefaultSectionSize(205)
        self.quote_2 = QtWidgets.QTextBrowser(searchUI)
        self.quote_2.setEnabled(False)
        self.quote_2.setGeometry(QtCore.QRect(30, 160, 181, 31))
        self.quote_2.setMouseTracking(False)
        self.quote_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.quote_2.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.quote_2.setAcceptDrops(False)
        self.quote_2.setAutoFillBackground(False)
        self.quote_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.quote_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.quote_2.setObjectName("quote_2")
        self.welcomeMessage.raise_()
        self.exit.raise_()
        self.quote.raise_()
        self.searchQuary.raise_()
        self.sendQuary.raise_()
        self.tableView.raise_()
        self.quote_2.raise_()

        self.retranslateUi(searchUI)
        QtCore.QMetaObject.connectSlotsByName(searchUI)

    def retranslateUi(self, searchUI):
        _translate = QtCore.QCoreApplication.translate
        searchUI.setWindowTitle(_translate("searchUI", "Coventry Research Search Engine"))
        self.welcomeMessage.setHtml(_translate("searchUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Calibri Light\',\'Calibri\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:20pt;\">Coventry University | Research Grid</span></p></body></html>"))
        self.exit.setText(_translate("searchUI", "Exit"))
        self.quote.setHtml(_translate("searchUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Calibri\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'-apple-system\',\'system-ui\',\'BlinkMacSystemFont\',\'Segoe UI\',\'Helvetica\',\'Arial\',\'sans-serif\',\'Apple Color Emoji\',\'Segoe UI Emoji\',\'Segoe UI Symbol\'; font-size:16pt; font-weight:296; color:#1a1a1a;\">“Wonder is the desire for knowledge.” – </span><a href=\"https://www.quoteambition.com/thomas-aquinas-quotes/\"><span style=\" font-family:\'-apple-system\',\'system-ui\',\'BlinkMacSystemFont\',\'Segoe UI\',\'Helvetica\',\'Arial\',\'sans-serif\',\'Apple Color Emoji\',\'Segoe UI Emoji\',\'Segoe UI Symbol\'; font-size:16pt; font-weight:296; text-decoration: underline; color:#5db873;\">Thomas Aquinas</span></a></p></body></html>"))
        self.sendQuary.setText(_translate("searchUI", "Search"))
        self.searchQuary.setHtml(_translate("searchUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Calibri\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\';\"><br /></p></body></html>"))
        self.searchQuary.setPlaceholderText(_translate("searchUI", "Search Everything..."))
        self.quote_2.setHtml(_translate("searchUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Calibri\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://www.quoteambition.com/thomas-aquinas-quotes/\"><span style=\" font-family:\'-apple-system\',\'system-ui\',\'BlinkMacSystemFont\',\'Segoe UI\',\'Helvetica\',\'Arial\',\'sans-serif\',\'Apple Color Emoji\',\'Segoe UI Emoji\',\'Segoe UI Symbol\'; font-size:10pt; font-weight:296; text-decoration: underline; color:#000000;\">Showing 100 result per search</span></a></p></body></html>"))
