# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setting.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.settings = QtWidgets.QTextBrowser(Form)
        self.settings.setEnabled(False)
        self.settings.setGeometry(QtCore.QRect(150, 10, 101, 31))
        self.settings.setMouseTracking(False)
        self.settings.setAcceptDrops(False)
        self.settings.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.settings.setObjectName("settings")
        self.currentVersionText = QtWidgets.QLabel(Form)
        self.currentVersionText.setGeometry(QtCore.QRect(30, 100, 101, 16))
        self.currentVersionText.setObjectName("currentVersionText")
        self.backButton = QtWidgets.QPushButton(Form)
        self.backButton.setGeometry(QtCore.QRect(20, 260, 75, 23))
        self.backButton.setObjectName("backButton")
        self.version = QtWidgets.QTextBrowser(Form)
        self.version.setEnabled(False)
        self.version.setGeometry(QtCore.QRect(140, 100, 101, 31))
        self.version.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.version.setMarkdown("")
        self.version.setObjectName("version")
        self.backButton_2 = QtWidgets.QPushButton(Form)
        self.backButton_2.setGeometry(QtCore.QRect(250, 100, 75, 23))
        self.backButton_2.setObjectName("backButton_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.settings.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Settings</span></p></body></html>"))
        self.currentVersionText.setText(_translate("Form", "Current version"))
        self.backButton.setText(_translate("Form", "Back"))
        self.version.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Calibri\';\"><br /></p></body></html>"))
        self.version.setPlaceholderText(_translate("Form", "0"))
        self.backButton_2.setText(_translate("Form", "Update"))
