# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'updating.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.updating_text = QtWidgets.QTextBrowser(Form)
        self.updating_text.setEnabled(False)
        self.updating_text.setGeometry(QtCore.QRect(150, 40, 101, 31))
        self.updating_text.setMouseTracking(False)
        self.updating_text.setAcceptDrops(False)
        self.updating_text.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.updating_text.setObjectName("updating_text")
        self.cancel_bton = QtWidgets.QPushButton(Form)
        self.cancel_bton.setGeometry(QtCore.QRect(140, 220, 121, 23))
        self.cancel_bton.setObjectName("cancel_bton")
        self.warning_massage = QtWidgets.QTextBrowser(Form)
        self.warning_massage.setEnabled(False)
        self.warning_massage.setGeometry(QtCore.QRect(110, 140, 171, 31))
        self.warning_massage.setMouseTracking(False)
        self.warning_massage.setAcceptDrops(False)
        self.warning_massage.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.warning_massage.setObjectName("warning_massage")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.updating_text.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Updating...</span></p></body></html>"))
        self.cancel_bton.setText(_translate("Form", "Cancel"))
        self.warning_massage.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Do not close Chrome</span></p></body></html>"))
